title: William Pedersen
#logo: /assets/img/profile3.png
#description: Welcome to my CV! Feel free to explore, and don't hesitate to reach out for collaboration. Email: william@live.dk. Phone: +45 29 28 57 45.
show_downloads: false
theme: jekyll-theme-minimal
